// ツールメトリクスのキューメッセージのスキーマ。
//
// Manifold は tools/call 1 回ごとに ToolCallEvent を 1 件、キューサービス
// （Amazon SQS / Redis Streams）へ送る。メッセージ本文は ToolCallEvent の
// Protocol Buffers 正規 JSON 表現（protojson）。受信側はこのファイルから
// 各言語のコードを生成し、その JSON パーサーで読み込む。
//
// 互換性のルール: フィールド番号は変更・再利用しない。フィールドの削除は
// reserved にする。後方互換のない変更は v2 パッケージとして追加する。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: manifold/toolmetrics/v1/tool_metrics.proto

package toolmetricsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolCallStatus は tools/call の終わり方の分類。
type ToolCallStatus int32

const (
	ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED ToolCallStatus = 0
	// ハンドラーが isError: false の結果を返した。
	ToolCallStatus_TOOL_CALL_STATUS_SUCCESS ToolCallStatus = 1
	// ハンドラーが isError: true の結果を返した（ツール自身が失敗を報告した。
	// 例: 上流の 4xx/5xx）。
	ToolCallStatus_TOOL_CALL_STATUS_TOOL_ERROR ToolCallStatus = 2
	// ハンドラーが JSON-RPC エラーを返した（認可拒否・未知のツール・
	// バックエンドに接続できない等）。
	ToolCallStatus_TOOL_CALL_STATUS_ERROR ToolCallStatus = 3
)

// Enum value maps for ToolCallStatus.
var (
	ToolCallStatus_name = map[int32]string{
		0: "TOOL_CALL_STATUS_UNSPECIFIED",
		1: "TOOL_CALL_STATUS_SUCCESS",
		2: "TOOL_CALL_STATUS_TOOL_ERROR",
		3: "TOOL_CALL_STATUS_ERROR",
	}
	ToolCallStatus_value = map[string]int32{
		"TOOL_CALL_STATUS_UNSPECIFIED": 0,
		"TOOL_CALL_STATUS_SUCCESS":     1,
		"TOOL_CALL_STATUS_TOOL_ERROR":  2,
		"TOOL_CALL_STATUS_ERROR":       3,
	}
)

func (x ToolCallStatus) Enum() *ToolCallStatus {
	p := new(ToolCallStatus)
	*p = x
	return p
}

func (x ToolCallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolCallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_manifold_toolmetrics_v1_tool_metrics_proto_enumTypes[0].Descriptor()
}

func (ToolCallStatus) Type() protoreflect.EnumType {
	return &file_manifold_toolmetrics_v1_tool_metrics_proto_enumTypes[0]
}

func (x ToolCallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolCallStatus.Descriptor instead.
func (ToolCallStatus) EnumDescriptor() ([]byte, []int) {
	return file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescGZIP(), []int{0}
}

// ToolCallEvent は tools/call 1 回分の記録。
type ToolCallEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// メッセージごとに一意な ID（UUID v7）。イベントの作成時に 1 回だけ発行し、
	// 再送でも同じ値を送る。配送は at-least-once のため、受信側はこの ID で
	// 重複を判定する。UUID v7 は先頭が作成時刻のミリ秒なので、文字列の辞書順が
	// 作成順になり、重複判定用のインデックスにもそのまま使える。
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// tools/call を受け付けた時刻。
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// サーバー名（mcpServers / agents のキー）。
	Server string `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	// サービスコード（mcpServers.<name>.service.code。未設定ならサーバー名）。
	Service string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	// ツール名。
	Tool string `protobuf:"bytes,5,opt,name=tool,proto3" json:"tool,omitempty"`
	// 呼び出し元ユーザー（authz.headers.userID ヘッダーの値）。無ければ空。
	User   string         `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Status ToolCallStatus `protobuf:"varint,7,opt,name=status,proto3,enum=manifold.toolmetrics.v1.ToolCallStatus" json:"status,omitempty"`
	// ハンドラーチェーンでかかった時間。
	Duration *durationpb.Duration `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	// JSON-RPC のエラーコード。status が TOOL_CALL_STATUS_ERROR の場合のみ設定する。
	ErrorCode int32 `protobuf:"varint,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// JSON-RPC エラーのメッセージ（TOOL_CALL_STATUS_ERROR）または結果のテキスト
	// （TOOL_CALL_STATUS_TOOL_ERROR）。1024 バイトで切り詰める。
	ErrorMessage string `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// OpenTelemetry のトレース ID（16 進 32 文字）。無ければ空。
	TraceId       string `protobuf:"bytes,11,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallEvent) Reset() {
	*x = ToolCallEvent{}
	mi := &file_manifold_toolmetrics_v1_tool_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEvent) ProtoMessage() {}

func (x *ToolCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_manifold_toolmetrics_v1_tool_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEvent.ProtoReflect.Descriptor instead.
func (*ToolCallEvent) Descriptor() ([]byte, []int) {
	return file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ToolCallEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ToolCallEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ToolCallEvent) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ToolCallEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ToolCallEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCallEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ToolCallEvent) GetStatus() ToolCallStatus {
	if x != nil {
		return x.Status
	}
	return ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED
}

func (x *ToolCallEvent) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ToolCallEvent) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ToolCallEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ToolCallEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_manifold_toolmetrics_v1_tool_metrics_proto protoreflect.FileDescriptor

const file_manifold_toolmetrics_v1_tool_metrics_proto_rawDesc = "" +
	"\n" +
	"*manifold/toolmetrics/v1/tool_metrics.proto\x12\x17manifold.toolmetrics.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x03\n" +
	"\rToolCallEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x12\n" +
	"\x04tool\x18\x05 \x01(\tR\x04tool\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12?\n" +
	"\x06status\x18\a \x01(\x0e2'.manifold.toolmetrics.v1.ToolCallStatusR\x06status\x125\n" +
	"\bduration\x18\b \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1d\n" +
	"\n" +
	"error_code\x18\t \x01(\x05R\terrorCode\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x19\n" +
	"\btrace_id\x18\v \x01(\tR\atraceId*\x8d\x01\n" +
	"\x0eToolCallStatus\x12 \n" +
	"\x1cTOOL_CALL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TOOL_CALL_STATUS_SUCCESS\x10\x01\x12\x1f\n" +
	"\x1bTOOL_CALL_STATUS_TOOL_ERROR\x10\x02\x12\x1a\n" +
	"\x16TOOL_CALL_STATUS_ERROR\x10\x03BQZOgithub.com/nonchan7720/manifold/pkg/proto/manifold/toolmetrics/v1;toolmetricsv1b\x06proto3"

var (
	file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescOnce sync.Once
	file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescData []byte
)

func file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescGZIP() []byte {
	file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescOnce.Do(func() {
		file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifold_toolmetrics_v1_tool_metrics_proto_rawDesc), len(file_manifold_toolmetrics_v1_tool_metrics_proto_rawDesc)))
	})
	return file_manifold_toolmetrics_v1_tool_metrics_proto_rawDescData
}

var file_manifold_toolmetrics_v1_tool_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_manifold_toolmetrics_v1_tool_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_manifold_toolmetrics_v1_tool_metrics_proto_goTypes = []any{
	(ToolCallStatus)(0),           // 0: manifold.toolmetrics.v1.ToolCallStatus
	(*ToolCallEvent)(nil),         // 1: manifold.toolmetrics.v1.ToolCallEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
}
var file_manifold_toolmetrics_v1_tool_metrics_proto_depIdxs = []int32{
	2, // 0: manifold.toolmetrics.v1.ToolCallEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: manifold.toolmetrics.v1.ToolCallEvent.status:type_name -> manifold.toolmetrics.v1.ToolCallStatus
	3, // 2: manifold.toolmetrics.v1.ToolCallEvent.duration:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_manifold_toolmetrics_v1_tool_metrics_proto_init() }
func file_manifold_toolmetrics_v1_tool_metrics_proto_init() {
	if File_manifold_toolmetrics_v1_tool_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifold_toolmetrics_v1_tool_metrics_proto_rawDesc), len(file_manifold_toolmetrics_v1_tool_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manifold_toolmetrics_v1_tool_metrics_proto_goTypes,
		DependencyIndexes: file_manifold_toolmetrics_v1_tool_metrics_proto_depIdxs,
		EnumInfos:         file_manifold_toolmetrics_v1_tool_metrics_proto_enumTypes,
		MessageInfos:      file_manifold_toolmetrics_v1_tool_metrics_proto_msgTypes,
	}.Build()
	File_manifold_toolmetrics_v1_tool_metrics_proto = out.File
	file_manifold_toolmetrics_v1_tool_metrics_proto_goTypes = nil
	file_manifold_toolmetrics_v1_tool_metrics_proto_depIdxs = nil
}
