name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up tools
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - name: Start dependencies
        run: docker compose up -d
      - name: Run lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          install-mode: "none"
          args: --timeout 5m --new-from-rev=origin/${{ github.base_ref }}
      - name: Create coverage directory
        run: mkdir -p coverage
      - name: Run tests
        run: make test
      - name: Shutdown dependencies
        if: always()
        run: docker compose down
